---
title: "FBI Active Shooters EDA"
author: "USAFacts"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkgload}
library(here)
library(tidyverse)
library(lubridate)
library(stringr)
library(viridis)
```

```{r read_data_initial, eval = FALSE}
active_shooters <- read_csv(here::here("fbi_active_shooter", "active_shooters.csv"))

active_shooters <- active_shooters %>%
  mutate(Date = str_replace_all(Date, pattern = "/", replacement = "-")) %>%
  unite("date_time", Date, Time, sep = " ") %>%
  mutate(date_time = mdy_hms(date_time)) %>%
  rename(event_name = `Active Shooter Event`,
         casualties = `Active Shooter Casualties`,
         wounded = `Active Shooter Wounded`,
         killed = `Active Shooter Killed`,
         city = City,
         state = State,
         location_type = `Location Type`,
         rifles = Rifles,
         shotguns = Shotguns,
         handguns = Handguns,
         explosives = Explosives,
         shooter_age = `Age of Shooter`,
         shooter_gender = `Gender of Shooter`)

if(sum(active_shooters$casualties != (active_shooters$wounded + active_shooters$killed)) != 0) {
active_shooters  <- active_shooters %>%
    mutate(casualties = ifelse(casualties != (wounded + killed), wounded + killed, casualties))

write_csv(active_shooters, here::here("fbi_active_shooter", "active_shooters_clean.csv"), append = FALSE)

}
```

```{r read_data_clean}
active_shooters <- read_csv(here::here("fbi_active_shooter", "active_shooters_clean.csv"))
```

```{r data_manipulation}
active_shooters <- active_shooters %>%
  mutate(year = year(date_time), 
         month = month(date_time), 
         hour = hour(date_time), 
         day = wday(date_time, label = TRUE),
         location_type = as_factor(location_type),
         shooter_gender = as_factor(shooter_gender),
         state = as_factor(state))

active_shooters <- active_shooters %>%
  mutate(state = fct_recode(state,
                            "Georgia" = "Georgio",
                            "Virginia" = "Virgina",
                            "Oklahoma" = "Oaklahoma",
                            "Washington D.C." = "D.C."),
         shooter_gender = fct_recode(shooter_gender,
                                     "Male" = "Mae"))
```

* Total incidents by year
* Wounded & Killed by year totals and on a per event basis
* Weapon counts by year
* Wounded & Killed by day of week and events by day of week


* Event distribution by gender
* Event distribution by age
* Top 10 events by casualties
* Number of casualties with only handguns used in events vs total casualties
* Map casualties per capita by state 

```{r incidents_by_year}
active_shooters %>% 
  select(event_name, year) %>%
  distinct() %>%
  group_by(year) %>%
  count() %>%
  filter(between(year, 2001, 2018)) %>%
  ggplot(aes(x = year, y = n)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Year", 
       y = "Active Shooter Events", 
       title = "The number of Active Shooter events per year has trended upwards", 
       subtitle = "In 2017 there was an Active Shooter event at a rate of over twice a month")
```

```{r casualties_by_year_and_type}
active_shooters %>%
  select(event_name, wounded, killed, year) %>%
  group_by(event_name, year) %>%
  summarise(wounded = sum(wounded), killed = sum(killed)) %>%
  gather(casualty_type, count, -event_name, -year) %>%
  ungroup() %>%
  group_by(year, casualty_type) %>%
  summarise(n = sum(count)) %>%
  filter(between(year, 2001, 2018)) %>%
  ggplot(aes(x = year, y = n, fill = casualty_type)) +
  geom_area() +
  scale_fill_viridis(discrete = TRUE, option = "E") +
  theme_minimal()
```

```{r firearms_by_year_and_type}
active_shooters %>%
  select(event_name, rifles, shotguns, handguns, explosives, year) %>%
  na.omit(.) %>%
  group_by(event_name, year) %>%
  summarise(rifles = sum(rifles), 
            shotguns = sum(shotguns), 
            handguns = sum(handguns), 
            explosives = sum(explosives)) %>%
  gather(firearms_type, count, -event_name, -year) %>%
  group_by(year, firearms_type) %>%
  summarise(n = sum(count)) %>%
  filter(between(year, 2001, 2018)) %>%
  ggplot(aes(x = year, y = n, fill = firearms_type)) +
  geom_col() +
  scale_fill_viridis(discrete = TRUE, option = "E") +
  theme_minimal()
```

```{r events_and_casualties_by_day}
active_shooters %>%
  select(killed, wounded, day) %>%
  group_by(day) %>%
  summarise(killed = sum(killed), wounded = sum(wounded)) %>%
  gather(casualty_type, count, -day) %>%
  ggplot(aes(x = day, y = count, fill = casualty_type)) +
  geom_col() +
  scale_fill_viridis(discrete = TRUE, option = "E") +
  theme_minimal()

active_shooters %>%
  select(killed, wounded, day, event_name) %>%
  group_by(day) %>%
  summarise(killed = sum(killed), wounded = sum(wounded), event_count = n()) %>%
  gather(casualty_type, count, -day, -event_count) %>%
  ggplot(aes(x = day, y = event_count)) +
  geom_col() +
  scale_fill_viridis(discrete = TRUE, option = "E") +
  theme_minimal()
```

```{r event_distribution_by_gender}

```

```{r event_distribution_by_age}

```